receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:

processors:
  batch:

connectors:
   graph:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [graph]
    metrics:
      receivers: [graph]
      exporters: [debug]
